apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job-random
  labels:
    kiamol: ch08
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      initContainers:
        - name: init-dp
          image: kiamol/ch03-sleep
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo $RANDOM > /init/dp']
          volumeMounts:
            - name: init
              mountPath: /init
      containers:
        - name: pi
          image: kiamol/ch05-pi
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'dotnet Pi.Web.dll -m console -dp $(cat /init/dp)']
          volumeMounts:
            - name: init
              mountPath: /init
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: init
          emptyDir: {}